[package]
name = "id3"
version = "0.5.1"
edition = "2018"
authors = [
    "polyfloyd <floyd@polyfloyd.net>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/polyfloyd/rust-id3"
description = "A library for reading and writing ID3 metadata"
keywords = ["id3", "audio", "parser", "metadata"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[features]
default = []
unstable = []

[dependencies]
bitflags = "1"
byteorder = "1"
flate2 = "1"

[dev-dependencies]
tempfile = "3"
